version: 1.0.{build}

environment:
  matrix:
  - PYTHON: c:\Python35\python.exe
  - PYTHON: c:\Python36\python.exe
  - PYTHON: c:\Python37\python.exe
  - PYTHON: c:\Python38\python.exe

build_script:
- '%PYTHON% run_unit_tests.py'
- '%PYTHON% run_func_tests.py -v'


